### ISSUE TITLE
Провести проверку на большом файле

### ISSUE THREAD

**Issue by alexkoss** [IS1DI/job#1]
Добрый день! Меня зовут Александр, сотрудник компании БалтИнфоКом.

Предлагаю осуществить проверку на большом файле.

Файл: https://github.com/PeacockTeam/new-job/releases/download/v1.0/lng-big.7z

В ответе должно быть количество групп и время выполнения.

**Comment by IS1DI** [comment]
Здравствуйте, количество групп: 105036 Время: 16 секунд
